//! Integration test: capture *real* loopback traffic generated by a process we
//! fully control (this test process itself, with a known PID) and assert per-PID
//! attribution plus TLS parsing end to end through the live pktap backend.
//!
//! This exercises what the engine-only tests can't: pktap header parsing, PID
//! filtering, link-type decode (loopback = DLT_NULL), and TLS reassembly over a
//! real socket — the exact pipeline that was silently dropping packets.
//!
//! Requires the macOS `pktap` interface, which needs root. Ignored by default;
//! run locally with:
//!
//!   sudo -E cargo test -p netmon --test capture_loopback -- --ignored --nocapture
//!
//! `pktap` must also surface loopback packets on your macOS version; if it
//! doesn't, the test says so rather than masquerading as a capture bug.
#![cfg(target_os = "macos")]

use std::io::{Read, Write};
use std::net::{TcpListener, TcpStream};
use std::thread;
use std::time::{Duration, Instant};

use netmon::source::PidFilter;
use netmon::{Session, SessionDelta};

mod common;
use common::{client_hello_record, target};

// A "server-like" port so the decoder classifies our ClientHello as outbound
// (see `server_like` in the engine); 8443 needs no privilege to bind.
const PORT: u16 = 8443;

#[test]
#[ignore = "needs root/pktap; run: sudo -E cargo test -p netmon --test capture_loopback -- --ignored"]
fn captures_our_own_loopback_clienthello() {
    // 1. A throwaway server on loopback that reads exactly one ClientHello.
    let listener =
        TcpListener::bind(("127.0.0.1", PORT)).expect("bind 127.0.0.1:8443 (already in use?)");
    let server = thread::spawn(move || {
        if let Ok((mut s, _)) = listener.accept() {
            let mut buf = [0u8; 4096];
            let _ = s.read(&mut buf); // consume the record; no response needed
        }
    });

    // 2. Start the direct pktap capture, filtered to *our own* PID.
    let rt = tokio::runtime::Runtime::new().expect("tokio runtime");
    let source = netmon::direct_capture_source();
    let filter = PidFilter {
        root_pid: std::process::id(),
        include_children: false,
    };
    let (mut rx, _handle) = match rt.block_on(source.start(filter)) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("SKIP: could not open pktap ({e}); run this test as root");
            let _ = server.join();
            return;
        }
    };

    // 3. Let the capture thread reach its read loop, then generate the traffic.
    thread::sleep(Duration::from_millis(300));
    {
        let mut c = TcpStream::connect(("127.0.0.1", PORT)).expect("connect");
        c.write_all(&client_hello_record()).expect("send ClientHello");
        c.flush().ok();
        // Hold the socket open briefly so the segment flushes before FIN.
        thread::sleep(Duration::from_millis(100));
    }

    // 4. Feed captured events through the engine until the handshake surfaces,
    //    surfacing the backend's diagnostics so a failure says which stage broke.
    let mut session = Session::new("loopback".into(), target(), "macos-pktap".into(), 0);
    let deadline = Instant::now() + Duration::from_secs(6);
    let mut handshake = None;
    let mut events = 0u32;
    let mut last_warning = None;
    while Instant::now() < deadline && handshake.is_none() {
        match rx.try_recv() {
            Ok(ev) => {
                events += 1;
                for d in session.ingest(ev) {
                    match d {
                        SessionDelta::Handshake(h) if h.sni.as_deref() == Some("example.com") => {
                            handshake = Some(h);
                        }
                        SessionDelta::Warning { message } => {
                            eprintln!("[capture warning] {message}");
                            last_warning = Some(message);
                        }
                        _ => {}
                    }
                }
            }
            Err(tokio::sync::mpsc::error::TryRecvError::Empty) => {
                thread::sleep(Duration::from_millis(50));
            }
            Err(tokio::sync::mpsc::error::TryRecvError::Disconnected) => break,
        }
    }

    let _ = server.join();
    eprintln!("captured {events} event(s); last diagnostic: {last_warning:?}");
    let hs = handshake.unwrap_or_else(|| {
        panic!(
            "no loopback ClientHello (SNI example.com) captured via pktap. \
             events={events}, last diagnostic={last_warning:?}"
        )
    });
    assert!(
        hs.destination.ends_with(&format!(":{PORT}")),
        "destination was {}",
        hs.destination
    );
    assert_eq!(hs.cipher_suites_offered, vec![0xC02F]);
}
